CREATE TABLE WC_UT_DAY_A
( 
START_DT_WID	        NUMBER(10,0),
START_DT		        DATE,
REPOSITORY_NAME		    VARCHAR2(128 BYTE),
SUBJECT_AREA_NAME		VARCHAR2(128 BYTE),
SUBJECT_AREA_NAME		NUMBER(10,0),
NODE_ID		            VARCHAR2(128 BYTE),
QUERY_SRC_CD		    VARCHAR2(30 BYTE) ,
SAW_SRC_PATH		    VARCHAR2(250 BYTE) ,
SAW_DASHBOARD		    VARCHAR2(150 BYTE) ,
SAW_DASHBOARD_PG		VARCHAR2(150 BYTE) ,
PRESENTATION_NAME		VARCHAR2(128 BYTE) ,
ERROR_TEXT		        VARCHAR2(250 BYTE) ,
IMPERSONATOR_USER_NAME	VARCHAR2(128 BYTE) ,
SERVICE_NAME		    VARCHAR2(128 BYTE),
SUCCESS_FLG             NUMBER(10,0),
ROW_COUNT               NUMBER(20,0),
TOTAL_TIME_SEC          NUMBER(10,0),
COMPILE_TIME_SEC        NUMBER(10,0),
NUM_DB_QUERY            NUMBER(10,0),
CUM_DB_TIME_SEC         NUMBER(10,0),
CUM_NUM_DB_ROW          NUMBER(20,0),
CACHE_IND_FLG           CHAR(1 BYTE),
NUM_CACHE_INSERTED      NUMBER(10,0) ,
NUM_CACHE_HITS          NUMBER(10,0) ,
TOTAL_TEMP_KB 			NUMBER(20,0) , 
RESP_TIME_SEC 			NUMBER(10,0) 
 )
 NOCOMPRESS NOLOGGING;
 