-- Author: Adrian Ward
-- Date: Feb 2020
-- Desc: Used to store the DAILY totals
CREATE TABLE WC_UT_DAY_A
( 
START_DT_WID	        NUMBER(10,0) NOT NULL,
START_DT		        DATE,
REPOSITORY_NAME		    VARCHAR2(128 BYTE) NOT NULL,
CACHE_IND_FLG           CHAR(1 BYTE) NOT NULL,
SUCCESS_FLG             NUMBER(10,0),
NUM_USERS               NUMBER(20,0),
NUM_QUERIES             NUMBER(20,0),
ROW_COUNT               NUMBER(20,0),
NUM_DASHBOARDS          NUMBER(20,0),
TOTAL_TIME_SEC          NUMBER(10,0),
AVG_TIME_SEC            NUMBER(10,0),
COMPILE_TIME_SEC        NUMBER(10,0),
NUM_DB_QUERY            NUMBER(10,0),
CUM_DB_TIME_SEC         NUMBER(10,0),
CUM_NUM_DB_ROW          NUMBER(20,0),
NUM_CACHE_INSERTED      NUMBER(10,0) ,
NUM_CACHE_HITS          NUMBER(10,0) ,
TOTAL_TEMP_KB 			NUMBER(20,0) , 
RESP_TIME_SEC 			NUMBER(10,0) 
 )
 NOCOMPRESS NOLOGGING;
ALTER TABLE WC_UT_DAY_A ADD CONSTRAINT WC_UT_DAY_A_PK PRIMARY KEY (START_DT_WID, REPOSITORY_NAME, CACHE_IND_FLG ) ENABLE;
CREATE INDEX WC_UT_DAY_A_IDX1 ON WC_UT_DAY_A (START_DT_WID);
