DROP TABLE WC_UT_DASHBOARD_DAY_A;

CREATE TABLE WC_UT_DASHBOARD_DAY_A
( 
    START_DT_WID	        NUMBER(10,0),
    START_DT		        DATE,
    REPOSITORY_NAME		    VARCHAR2(128 BYTE),
    SAW_DASHBOARD		    VARCHAR2(150 BYTE) ,
    SAW_DASHBOARD_PG		VARCHAR2(150 BYTE) ,
    DASHBOARD_WID           NUMBER(10,0),
    DASHBOARD_PAGE_WID      NUMBER(10,0),
    NUM_USERS               NUMBER(20,0),
    NUM_QUERIES             NUMBER(20,0),
    AVG_TIME_SEC            NUMBER(10,0),
    ROW_COUNT               NUMBER(20,0),
    TOTAL_TIME_SEC          NUMBER(10,0),
    COMPILE_TIME_SEC        NUMBER(10,0),
    NUM_DB_QUERY            NUMBER(10,0),
    CUM_DB_TIME_SEC         NUMBER(10,0),
    CUM_NUM_DB_ROW          NUMBER(20,0),
    NUM_CACHE_INSERTED      NUMBER(10,0),
    NUM_CACHE_HITS          NUMBER(10,0),
    TOTAL_TEMP_KB 			NUMBER(20,0), 
    RESP_TIME_SEC 			NUMBER(10,0)
 )
 NOCOMPRESS NOLOGGING;
 
CREATE INDEX    WC_UT_DASHBOARD_DAY_A_IDX1 ON WC_UT_DASHBOARD_DAY_A (START_DT_WID);
CREATE INDEX    WC_UT_DASHBOARD_DAY_A_IDX2 ON WC_UT_DASHBOARD_DAY_A (START_DT);
CREATE INDEX    WC_UT_DASHBOARD_DAY_A_IDX3 ON WC_UT_DASHBOARD_DAY_A (DASHBOARD_WID);
CREATE INDEX    WC_UT_DASHBOARD_DAY_A_IDX4 ON WC_UT_DASHBOARD_DAY_A (DASHBOARD_PAGE_WID);
