-- Created by Adrian Ward, Addidici - http://blog.obiee.info

-- Insert a Zero row.  
INSERT INTO G_DATE  (DATE_WID, CAL_DATE, DAY_NAME, MONTH_NAME, MONTH_NUMBER, YEAR_NUMBER, DAY_OF_WEEK, DAY_OF_MONTH, DAY_OF_YEAR, WEEK_OF_YEAR, QUARTER_OF_YEAR, YEAR_MONTH, WEEK_WID )  VALUES  ( 0, '01-JAN-1900', 'Unknown','Unknown',0,0,0,0,0,0,0,0,0);
commit;

-- Fill G_DATE with calculated data
INSERT INTO G_DATE
SELECT
TO_NUMBER(TO_CHAR(CURRDATE, 'YYYYMMDD')) 	AS DATE_WID,
CURRDATE 					AS CAL_DATE,
TO_CHAR(CURRDATE,'DAY') 			AS DAY_NAME,
TO_CHAR(CURRDATE,'MONTH') 			AS MONTH_NAME,
TO_NUMBER(TO_CHAR(CURRDATE,'MM')) 		AS MONTH_NUMBER,
TO_NUMBER(TO_CHAR(CURRDATE,'YYYY')) 		AS YEAR_NUMBER,
TO_NUMBER(TO_CHAR(CURRDATE,'D')) 		AS DAY_OF_WEEK,
TO_NUMBER(TO_CHAR(CURRDATE,'DD')) 		AS DAY_OF_MONTH,
TO_NUMBER(TO_CHAR(CURRDATE,'DDD')) 		AS DAY_OF_YEAR,
TO_NUMBER(TO_CHAR(CURRDATE+1,'IW')) 		AS WEEK_OF_YEAR,
TO_NUMBER((TO_CHAR(CURRDATE,'Q'))) 		AS QUARTER_OF_YEAR,
ADD_MONTHS(CURRDATE, -12) 			AS YEAR_AGO_DATE,
ADD_MONTHS(CURRDATE, -1) 			AS MONTH_AGO_DATE,
CURRDATE - 7 					AS WEEK_AGO_DATE,
CURRDATE - 1 					AS DAY_AGO_DATE,
CURRDATE + 1 					AS NEXT_DAY_DATE,
CURRDATE + 7 					AS NEXT_WEEK_DATE,
ADD_MONTHS(CURRDATE, 1) 			AS NEXT_MONTH_DATE,
ADD_MONTHS(CURRDATE, 12) 			AS NEXT_YEAR_DATE,
TRUNC (CURRDATE, 'MM')				AS CUR_MONTH_FIRST_DATE,
LAST_DAY(CURRDATE)				AS CUR_MONTH_LAST_DATE,
TRUNC(CURRDATE, 'Y')				AS CUR_YEAR_FIRST_DATE,
TO_NUMBER(TO_CHAR(CURRDATE, 'YYYYMM')) 		AS YEAR_MONTH,
TO_NUMBER(TO_CHAR(CURRDATE, 'YYYYWW'))	AS WEEK_WID
FROM (
SELECT LEVEL N, TO_DATE('31/12/1990','DD/MM/YYYY') + NUMTODSINTERVAL(LEVEL,'DAY') CURRDATE
FROM DUAL
CONNECT BY LEVEL <= 40000)
ORDER BY 1;
commit;

