-- AS BIPLATFORM Owner
INSERT INTO wc_ut_details (
    user_name,
    repository_name,
    subject_area_name,
    node_id,
    start_ts,
    start_dt,
    start_hour_min,
    end_ts,
    end_dt,
    end_hour_min,
    query_text,
    query_blob,
    query_key,
    success_flg,
    row_count,
    total_time_sec,
    compile_time_sec,
    num_db_query,
    cum_db_time_sec,
    cum_num_db_row,
    cache_ind_flg,
    query_src_cd,
    saw_src_path,
    saw_dashboard,
    saw_dashboard_pg,
    presentation_name,
    error_text,
    impersonator_user_name,
    num_cache_inserted,
    num_cache_hits,
    id,
    ecid,
    tenant_id,
    service_name,
    session_id,
    hash_id,
    total_temp_kb,
    resp_time_sec,
    start_dt_wid
) 
SELECT
    user_name,
    repository_name,
    subject_area_name,
    node_id,
    start_ts,
    start_dt,
    start_hour_min,
    end_ts,
    end_dt,
    end_hour_min,
    query_text,
    query_blob,
    query_key,
    success_flg,
    row_count,
    total_time_sec,
    compile_time_sec,
    num_db_query,
    cum_db_time_sec,
    cum_num_db_row,
    cache_ind_flg,
    query_src_cd,
    saw_src_path,
    saw_dashboard,
    saw_dashboard_pg,
    presentation_name,
    error_text,
    impersonator_user_name,
    num_cache_inserted,
    num_cache_hits,
    id,
    ecid,
    tenant_id,
    service_name,
    session_id,
    hash_id,
    total_temp_kb,
    resp_time_sec,
    to_number(to_char(start_dt, 'YYYYMMDD')) start_dt_WID
FROM
    s_nq_acct;

update wc_ut_details utd
set dashboard_wid = (SELECT ROW_WID FROM WC_UT_DASHBOARDS d where d.dashboard)
where trunc(start_dt) => trunc(sysdate)-1;

-- Truncate s_nq_acct
-- as user BIPLATFORM
truncate table s_nq_acct;
