--------------------------------------------------------
--  DDL for Table S_NQ_ACCT
--------------------------------------------------------

  CREATE TABLE "OBI_BIPLATFORM"."S_NQ_ACCT" 
   (	"USER_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"REPOSITORY_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBJECT_AREA_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"NODE_ID" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"START_TS" DATE, 
	"START_DT" DATE, 
	"START_HOUR_MIN" CHAR(5 BYTE) COLLATE "USING_NLS_COMP", 
	"END_TS" DATE, 
	"END_DT" DATE, 
	"END_HOUR_MIN" CHAR(5 BYTE) COLLATE "USING_NLS_COMP", 
	"QUERY_TEXT" VARCHAR2(1024 BYTE) COLLATE "USING_NLS_COMP", 
	"QUERY_BLOB" CLOB COLLATE "USING_NLS_COMP", 
	"QUERY_KEY" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"SUCCESS_FLG" NUMBER(10,0), 
	"ROW_COUNT" NUMBER(20,0), 
	"TOTAL_TIME_SEC" NUMBER(10,0), 
	"COMPILE_TIME_SEC" NUMBER(10,0), 
	"NUM_DB_QUERY" NUMBER(10,0), 
	"CUM_DB_TIME_SEC" NUMBER(10,0), 
	"CUM_NUM_DB_ROW" NUMBER(20,0), 
	"CACHE_IND_FLG" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'N', 
	"QUERY_SRC_CD" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"SAW_SRC_PATH" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"SAW_DASHBOARD" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"SAW_DASHBOARD_PG" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"PRESENTATION_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"ERROR_TEXT" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"IMPERSONATOR_USER_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"NUM_CACHE_INSERTED" NUMBER(10,0) DEFAULT null, 
	"NUM_CACHE_HITS" NUMBER(10,0) DEFAULT null, 
	"ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ECID" VARCHAR2(1024 BYTE) COLLATE "USING_NLS_COMP", 
	"TENANT_ID" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"SERVICE_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"SESSION_ID" NUMBER(10,0), 
	"HASH_ID" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL_TEMP_KB" NUMBER(20,0) DEFAULT null, 
	"RESP_TIME_SEC" NUMBER(10,0) DEFAULT null
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "OBI_BIPLATFORM" 
 LOB ("QUERY_BLOB") STORE AS SECUREFILE (
  TABLESPACE "OBI_BIPLATFORM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Index S_NQ_ACCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OBI_BIPLATFORM"."S_NQ_ACCT_PK" ON "OBI_BIPLATFORM"."S_NQ_ACCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "OBI_BIPLATFORM" ;
--------------------------------------------------------
--  DDL for Index S_NQ_ACCT_M1
--------------------------------------------------------

  CREATE INDEX "OBI_BIPLATFORM"."S_NQ_ACCT_M1" ON "OBI_BIPLATFORM"."S_NQ_ACCT" ("START_DT", "START_HOUR_MIN", "USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "OBI_BIPLATFORM" ;
--------------------------------------------------------
--  DDL for Index S_NQ_ACCT_M2
--------------------------------------------------------

  CREATE INDEX "OBI_BIPLATFORM"."S_NQ_ACCT_M2" ON "OBI_BIPLATFORM"."S_NQ_ACCT" ("START_HOUR_MIN", "USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "OBI_BIPLATFORM" ;
--------------------------------------------------------
--  DDL for Index S_NQ_ACCT_M3
--------------------------------------------------------

  CREATE INDEX "OBI_BIPLATFORM"."S_NQ_ACCT_M3" ON "OBI_BIPLATFORM"."S_NQ_ACCT" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "OBI_BIPLATFORM" ;
--------------------------------------------------------
--  Constraints for Table S_NQ_ACCT
--------------------------------------------------------

  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_ACCT" MODIFY ("CACHE_IND_FLG" NOT NULL ENABLE);
  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_ACCT" ADD CONSTRAINT "S_NQ_ACCT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "OBI_BIPLATFORM"  ENABLE;
