--------------------------------------------------------
--  DDL for Table S_NQ_SUMMARY_ADVISOR
--------------------------------------------------------

  CREATE TABLE "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" 
   (	"VERSION" CHAR(32 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"LOGICALFACTTABLEID" CHAR(255 BYTE) COLLATE "USING_NLS_COMP" DEFAULT '', 
	"LOGICALTABLESOURCEIDVECTOR" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESSINGTIMEINMILLISEC" NUMBER(10,0) DEFAULT 0, 
	"QUERYLEVELIDVECTOR" CLOB COLLATE "USING_NLS_COMP", 
	"SOURCECELLLEVELIDVECTOR" CLOB COLLATE "USING_NLS_COMP", 
	"LOGICAL_QUERY_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"QUERYSTATUS" NUMBER(10,0) DEFAULT 0, 
	"GROUPBYCOLUMNIDVECTOR" CLOB COLLATE "USING_NLS_COMP", 
	"MEASURECOLUMNIDVECTOR" CLOB COLLATE "USING_NLS_COMP", 
	"ROW_COUNT" NUMBER(20,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "OBI_BIPLATFORM" 
 LOB ("QUERYLEVELIDVECTOR") STORE AS SECUREFILE (
  TABLESPACE "OBI_BIPLATFORM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("SOURCECELLLEVELIDVECTOR") STORE AS SECUREFILE (
  TABLESPACE "OBI_BIPLATFORM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("GROUPBYCOLUMNIDVECTOR") STORE AS SECUREFILE (
  TABLESPACE "OBI_BIPLATFORM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("MEASURECOLUMNIDVECTOR") STORE AS SECUREFILE (
  TABLESPACE "OBI_BIPLATFORM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Index S_NQ_SUMMARY_ADVISOR_I1
--------------------------------------------------------

  CREATE INDEX "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR_I1" ON "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" ("LOGICAL_QUERY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "OBI_BIPLATFORM" ;
--------------------------------------------------------
--  Constraints for Table S_NQ_SUMMARY_ADVISOR
--------------------------------------------------------

  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" MODIFY ("ROW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" MODIFY ("LOGICALFACTTABLEID" NOT NULL ENABLE);
  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" MODIFY ("PROCESSINGTIMEINMILLISEC" NOT NULL ENABLE);
  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" MODIFY ("QUERYSTATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table S_NQ_SUMMARY_ADVISOR
--------------------------------------------------------

  ALTER TABLE "OBI_BIPLATFORM"."S_NQ_SUMMARY_ADVISOR" ADD CONSTRAINT "FK_S_NQ_SUMMARY_ADVISOR" FOREIGN KEY ("LOGICAL_QUERY_ID")
	  REFERENCES "OBI_BIPLATFORM"."S_NQ_ACCT" ("ID") ON DELETE CASCADE ENABLE;
