--------------------------------------------------------
--  DDL for Table S_NQ_INITBLOCK
--------------------------------------------------------

  CREATE TABLE "OBI_BIPLATFORM"."S_NQ_INITBLOCK" 
   (	"USER_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"REPOSITORY_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"TENANT_ID" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"SERVICE_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"ECID" VARCHAR2(1024 BYTE) COLLATE "USING_NLS_COMP", 
	"SESSION_ID" NUMBER(10,0), 
	"BLOCK_NAME" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"START_TS" TIMESTAMP (6), 
	"END_TS" TIMESTAMP (6), 
	"DURATION" NUMBER(13,3), 
	"NOTES" VARCHAR2(1024 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "OBI_BIPLATFORM" ;
