--------------------------------------------------------
--  DDL for Table S_NQ_DB_ACCT
--------------------------------------------------------

  CREATE TABLE "OBI_BIPLATFORM"."S_NQ_DB_ACCT" 
   (	"ID" NUMBER(10,0), 
	"LOGICAL_QUERY_ID" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"QUERY_TEXT" VARCHAR2(1024 BYTE) COLLATE "USING_NLS_COMP", 
	"QUERY_BLOB" CLOB COLLATE "USING_NLS_COMP", 
	"TIME_SEC" NUMBER(10,0), 
	"ROW_COUNT" NUMBER(20,0), 
	"START_TS" DATE, 
	"START_DT" DATE, 
	"START_HOUR_MIN" CHAR(5 BYTE) COLLATE "USING_NLS_COMP", 
	"END_TS" DATE, 
	"END_DT" DATE, 
	"END_HOUR_MIN" CHAR(5 BYTE) COLLATE "USING_NLS_COMP", 
	"HASH_ID" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PHYSICAL_HASH_ID" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "OBI_BIPLATFORM" 
 LOB ("QUERY_BLOB") STORE AS SECUREFILE (
  TABLESPACE "OBI_BIPLATFORM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
