CREATE TABLE S_NQ_DB_ACCT
( ID NUMBER(10,0),
LOGICAL_QUERY_ID VARCHAR2(50 BYTE),
QUERY_TEXT VARCHAR2(1024 BYTE),
QUERY_BLOB CLOB,
TIME_SEC NUMBER(10,0),
ROW_COUNT NUMBER(20,0),
START_TS DATE,
START_DT DATE,
START_HOUR_MIN CHAR(5 BYTE),
END_TS DATE,
END_DT DATE,
END_HOUR_MIN CHAR(5 BYTE),
HASH_ID VARCHAR2(128 BYTE),
PHYSICAL_HASH_ID VARCHAR2(128 BYTE);
CREATE INDEX S_NQ_DB_ACCT_I1 ON OBIW.S_NQ_DB_ACCT (LOGICAL_QUERY_ID);

ALTER TABLE S_NQ_DB_ACCT ADD CONSTRAINT FK_S_NQ_DB_ACCT FOREIGN KEY (LOGICAL_QUERY_ID);
